on:
  push:
    branches: [ master ]

jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    name: publiccode.yml validation
    steps:
    - uses: actions/checkout@v4
    - uses: italia/publiccode-parser-action@v1
